### PR TITLE
modifed setting of predecessors that only one predecessor can be set

### PR DESCRIPTION
**Pull request by lorikdumani**
If there are multiple choices always the first block that has not been set yet will be selected.

### CODE REVIEW

**Comment by sbaltes** [comment]
Thanks for fixing this bug!

In case all matching post blocks from the previous version are already assigned as a predecessor of other post blocks in the current version, no predecessor will be set. Is that correct?

**Comment by lorikdumani** [comment]
Yes, that's correct.

**Comment by sbaltes** [comment]
Example where two equal text blocks exist in both versions:

twoequalblocksineachversion

**Comment by sbaltes** [comment]
Other possible scenario:

Two post blocks in version i+1 have one common predecessor in version i. With this fix, only the first post block would have a predecessor, the second not. One disadvantage of this solution is that `predCount` would be >0, but no predecessor is linked. Would you still do the change?

**Comment by lorikdumani** [comment]
This could be the following scenario:

examplemultiplelinkspossible

In this case we could considerate two variables:
One for possible links and one for set links.

**Comment by sbaltes** [comment]
Thanks for the example. I guess one could argue that here, the first code block should be connected. The second code block does not have a "real" predecessor, just a possible match.

Could you add a test case for post 42070509 and update the pull request? I'll merge the pull request afterwards.

**Comment by lorikdumani** [comment]
You're welcome.
The output when computed would be the following:

    versions: 0 and 1
    connections: 2 <- 2
    connections: 3 <- 3
    connections: 5 <- 5
    connections: 6 <- 6
    connections: 8 <- 8
    connections: 9 <- 9
    connections: null <- 11
    connections: null <- 12

**Pull request merged**
